### ISSUE TITLE
[1.12] Crash with Forge 2389

### ISSUE THREAD

**Issue by MokahTGS** [chazwarp923/Unified-Items#12]
Getting a crash with Forge v2389

https://pastebin.com/SPcQCKAL

**Comment by chazwarp923** [comment]
Loading up dev environment now. Looks like forge removed something. Fix hopefully up within the hour

**Comment by chazwarp923** [comment]
Fixed in 1.6.1

**Comment by chazwarp923** [comment]
Actually, don't use that, missed one thing, use 1.6.2 when its up
