### ISSUE TITLE
Null Pointer Exception when grinding Ore to Dust with Mortar and Pestle

### ISSUE THREAD

**Issue by Zarepheth** [chazwarp923/Unified-Items#4]
On the crafting table, when attempting to use a Mortar and Pestle to grind Gold ore into Gold Powder/Dust, the game crashed. The crash report claims a Null Pointer Exception. I had just clicked the right mouse button, intending to have JEI display the recipes which use the Gold Powder/Dust - but since I wasn't paying much attention and my mouse was in the crafting UI rather than JEI's recipe UI, the game attempted to craft the Gold Powder/Dust - then crashed before I could do anything else.

[crash-2017-01-09_22.44.09-client.txt](https://github.com/chazwarp923/Unified-Items/files/695289/crash-2017-01-09_22.44.09-client.txt)

[fml-client-latest-2.log.txt](https://github.com/chazwarp923/Unified-Items/files/695291/fml-client-latest-2.log.txt)

_UPDATE:_

After returning to the game I found stack of Gold Ore had shrunk from 8 ore to 5 and the Mortar and Pestle had only 1 durable left (out of 4). So something attempted to create the dust/powder. Also, after returning to the game, I tried the recipe again - this time in the 2x2 inventory crafting grid and using a single Gold Ore instead of a stack. I got the same crash.

[crash-2017-01-09_23.05.06-client.txt](https://github.com/chazwarp923/Unified-Items/files/695315/crash-2017-01-09_23.05.06-client.txt)

**Comment by chazwarp923** [comment]
I'm 99% sure this is due to the jei plugin bugging out. I'll take a look at it in the morning. For now just stay away from using the mortar and pestle and you should be fine.

**Comment by chazwarp923** [comment]
This is fixed in 1.4.5
bbabad7ccb4c0e234a57a9a1fa55a8ed00f4d977
