### ISSUE TITLE
Lead, Silver and Uranium ores require a Diamond pickaxe for some reason.

### ISSUE THREAD

**Issue by Dukat863** [chazwarp923/Unified-Items#5]
This seems a bit extreme when compared to other mods, especially for a soft metal like Lead.

Mod version is 1.4.5-129, which is latest at the time of writing.

**Comment by chazwarp923** [comment]
I can see your argument for lead and silver, however i don't see the need in lowering the mining level of uranium. I say that because it isn't really useful until mid-late game anyways so whats the point of mining it in early game.
