### ISSUE TITLE
Mortar and Pestle not working

### ISSUE THREAD

**Issue by P3t3rU5** [chazwarp923/Unified-Items#8]
Hey there,

Was trying to use the mortar and pestle and got this error:

https://paste.ee/p/2u6tf

**Comment by chazwarp923** [comment]
I can't be sure, since I'm at work. But from what I can tell it looks to be mantle messing with something. I'll test when I get home to confirm

**Comment by P3t3rU5** [comment]
i thought so as well, and thought it had anything to do with using tinkers crafting station, but then i tested with vanilla crafting table and it crashed as well, I have crafting tweaks installed too, maybe that's conflicting? gonna test without it.

**Comment by chazwarp923** [comment]
Well I see mantle further down the stack trace from my class but it's crashing on a vanilla method in my class, something I never changed. That's why I think it's probably Mantle.

**Comment by chazwarp923** [comment]
Okay, upon further inspection, it is my fault. A method in IRecipe returns a different thing in 1.10.2 and 1.11.2. 
I've made a fix and submitted it as a pull request to compatlayer [here](https://github.com/McJty/compatlayer/pull/4). When/if he merges that I'll push a new version to fix this.

**Comment by P3t3rU5** [comment]
Thanks 😁

**Comment by chazwarp923** [comment]
This is now fixed in 1.4.8, should be up on curse as soon as they approve it.
